#!/bin/bash

if [ -z "$1" ]; then
    echo usage: moss -d \<lab_directory\> \[-i \<basefile1\>, ... , \<basefileN\>\]
    exit 1
fi
BASE=false
# getopts tutorial
# http://wiki.bash-hackers.org/howto/getopts_tutorial
# while loop modified from above source
while getopts ":d:b" opt; do
  case $opt in
    d)
      DIR=$OPTARG
      ;;
    b)
      # TODO: Determine whether the base code will always be in this folder
      cat ./$DIR/instructor/resources/code/*.s > ./$DIR/instructor/base.s
      BASE=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ $BASE = true ]; then
  # $RESULTS = the url returned by moss
  RESULTS=$(./moss -l mips -b ./$DIR/instructor/base.s -d ./$DIR/*/resources/code/*.s | grep '^http')
else
  RESULTS=$(./moss -l mips ./$DIR/*/*/*/*.s | grep '^http')
fi
# The results page is saved locally in the lab directory as results.html
# curl -s -o "./$DIR/results.html" -L $RESULTS
# Noah's wget command
# wget -e robots=off -m http://moss.stanford.edu/results/134412096/
wget -e robots=off -k $RESULTS # --directory-prefix=./results/ # --output-document=./$DIR/results.html

# ./moss -l mips ./$DIR/*.s | grep '^http' > $OUTPUTDIR
# ./moss -l mips ./simple/*.s | grep '^http' > output.txt
