#!/bin/bash

if [ -z "$1" ]; then
    echo usage: moss -d \<lab_directory\> \[-i \<basefile1\>, ... , \<basefileN\>\]
    exit 1
fi
BASE=false
# getopts tutorial
# http://wiki.bash-hackers.org/howto/getopts_tutorial
# while loop modified from above source
while getopts ":d:b" opt; do
  case $opt in
    d)
      DIR=$OPTARG
      ;;
    b)
      BASE=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ $BASE = true ]; then
  echo "!!!"
  # $RESULTS = the url returned by moss
  RESULTS=$(./moss -l mips -b ./$DIR/instructor/base.s ./$DIR/*/submission/*.s | grep '^http')
else
  RESULTS=$(./moss -l mips ./$DIR/*/submission/*.s | grep '^http')
fi
# The results page is saved locally in the lab directory as results.html
wget -e robots=off -p -r --quiet --convert-links $RESULTS -nH -nd --directory-prefix=./results/

# ./moss -l mips ./$DIR/*.s | grep '^http' > $OUTPUTDIR
# ./moss -l mips ./simple/*.s | grep '^http' > output.txt
