#!/bin/bash

# Calling expectation: moss -l <lang> -b <base> -d <dir1 ... dirn>

# getopts tutorial
# http://wiki.bash-hackers.org/howto/getopts_tutorial
# while loop modified from above source
# comparisons: http://tldp.org/LDP/abs/html/comparison-ops.html
#
# segment from args:
# http://stackoverflow.com/questions/2390738/bash-argument-list-segment
# user: ghostdog74

# Expectation: Base code in ./$DIR/instructor/base.s
# Expectation: Student submissions in ./$DIR/*/submission/
# $RESULTS = the url returned by moss

# The results page is saved locally in the lab directory as results.html
# curl -s -o "./$DIR/results.html" -L $RESULTS
# Noah's wget command
# wget -e robots=off -m http://moss.stanford.edu/results/134412096/
# More wget info: 
# https://www.gnu.org/software/wget/manual/html_node/Advanced-Usage.html

echo "$@"

LANG=$1
BASE=$2
# DIRS="${@:3}"

echo "BASE: $BASE"

RESULTS=$(moss -l $LANG -b $BASE -d $DIRS | grep '^http')
wget -e robots=off -p -r --quiet --convert-links $RESULTS -nH -nd --directory-prefix=./results/

